### ISSUE TITLE
for livox lidar

### ISSUE THREAD

**Issue by chengwei0427** [tiev-tongji/RingFalsNormal#5]
Hi, @Freddd13 @h-k8888 
 
        Nice work and thanks for sharing.

        I am wonder if this method is suitable for livox lidar, like mid-360, avia ?

**Comment by chengwei0427** [comment]
**Another question:**
The normal vectors of some laser points are miscalculated,as shown in the following picture [**Different views of the same data**]
![image](https://github.com/tiev-tongji/RingFalsNormal/assets/20199999/a1bf71b7-c2ab-4806-8fff-e0638bd82de7)
![2024-02-04 14-27-07屏幕截图](https://github.com/tiev-tongji/RingFalsNormal/assets/20199999/16feecb3-31d5-4aaa-a1a6-062a3aff5dd5)

Maybe part of the error is because the normal vector is close to **90** degrees.
But as you can see, some of the angles are less than **90** degrees.Do you have any good suggestions for this problem?

**Comment by h-k8888** [comment]
@chengwei0427 
This method is probably not working well for livox since its mechanism is repeated scanning, but it's still a good idea to give it a try.
The wrong estimate for RingFals probably comes from the fact that some pixels in the range image corresponding to the scan have no range value. Using a low-resolution range image should alleviate this, but that would not be estimating the normal at every point within the scan.

**Comment by chengwei0427** [comment]
Thank you for your patience, problem solved.
